[package]
name = "rust_vulkan"
version = "0.1.0"
edition = "2024"

[lib]
name = "rust_vulkan"
crate-type = ["cdylib"]

[dependencies]
# Vulkan dependencies
ash = "0.38.0"

# Tool dependencies
cfg-if = "1.0.4"

# Logger dependencies
log = "0.4.28"
env_logger = "0.11.8"