[target.aarch64-unknown-linux-ohos]
linker = "D:\\DevEco Studio\\sdk\\default\\openharmony\\native\\llvm\\bin\\clang.exe"
ar = "D:\\DevEco Studio\\sdk\\default\\openharmony\\native\\llvm\\bin\\llvm-ar.exe"
rustflags = [
    "-C", "link-arg=--target=aarch64-linux-ohos",
    "-C", "link-arg=--sysroot=D:\\DevEco Studio\\sdk\\default\\openharmony\\native\\sysroot",
    "-C", "link-arg=-fuse-ld=lld"
]